name: 'Airen Kang'
description: 'GitHub action for release automation'
author: 'Airen Kang'
inputs:
  gh_token:
    required: true
    description: 'Input GitHub access token here'
  circleci_token:
    required: true
    description: 'Input CircleCI API token here'
runs:
  using: 'node16'
  main: 'dist/index.js'
