name: 'release-automation-action'
description: 'GitHub action for release automation'
author: 'Airen Kang'
inputs:
  gh_token:
    required: true
    description: 'Input GitHub access token here'
  circleci_token:
    required: true
    description: 'Input CircleCI API token here'
  platform:
    required: true
    description: 'Input SDK platform here, e.g. ios, android, js, rn, flutter'
  product:
    required: true
    description: 'Input SDK product here, e.g. chat, calls, uikit, live, live_uikit'
  product_jira_project_key:
    required: true
    description: 'Input product jira project key here, e.g. CORE, UIKIT, CALLS, PLATFORMX'
  product_jira_version_prefix:
    required: false
    description: 'Input custom product jira release version prefix here, e.g. ios_core, rn_uikit, js_uikit. (default: {product}-{platform}[-{framework}]?)'
  framework:
    required: false
    description: 'Input SDK framework here, e.g. react'
  test:
    required: false
    description: 'Input actions run on testing environment'
    default: 'false'
  changelog_file:
    required: false
    description: 'Input changelog file name. (e.g. CHANGELOG_KTX_DRAFT.md) Default is CHANGELOG_DRAFT.md.'
    default: 'CHANGELOG_DRAFT.md'
  ci:
    required: false
    description: 'Input CI name. (e.g. circleci, github) Default is circleci.'
    default: 'circleci'
runs:
  using: 'node16'
  main: 'dist/index.js'
