name: PR Comment Bot
on:
  issue_comment:
    types: [created]
jobs:
  pr-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          gh_token: ${{ secrets.BOT_GH_TOKEN }}
          circleci_token: ${{ secrets.CIRCLECI_TOKEN }}
          product: 'uikit'
          platform: 'rn'
          product_jira_project_key: 'UIKIT'
          product_jira_version_prefix: 'rn_uikit'
          test: true
