name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create and push release branch
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git checkout -b "release/$VERSION"
          git push --set-upstream origin "release/$VERSION"
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn install --immutable
      - name: 'set environments'
        run: |
          git config --global user.name "sendbird-sdk-deployment"
          git config --global user.email "sha.sdk_deployment@sendbird.com"
      - name: 'publish to github'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          yarn release-it "$VERSION" --ci
      - name: Tag new target
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: git tag -f latest "$VERSION"
      - name: Push new tag
        run: git push origin latest --force
      - name: 'create a pull request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          gh pr create --title "chore(release): publish $VERSION" --body "created by automation"
