name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push --set-upstream origin release/${{ github.event.inputs.version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: yarn install --immutable
      - name: 'set environments'
        run: |
          git config --global user.name "sendbird-sdk-deployment"
          git config --global user.email "sha.sdk_deployment@sendbird.com"
      - name: 'publish to github'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn release-it ${{ github.event.inputs.version }} --ci
      - name: Tag new target
        run: git tag -f latest ${{ github.event.inputs.version }}
      - name: Push new tag
        run: git push origin latest --force
      - name: 'create a pull request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "chore(release): publish ${{ github.event.inputs.version }}" --body "created by automation"
