name: Release workflow example

on:
  workflow_dispatch:
    inputs:
      release_ticket_key:
        description: 'Release ticket key'
        required: true
        type: string
      is_test:
        description: 'Is this a test?'
        required: true
        type: boolean

jobs:
  echo-release:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        env:
          RELEASE_TICKET_KEY: ${{ inputs.release_ticket_key }}
          IS_TEST: ${{ inputs.is_test }}
        run: |
          echo "release_ticket_key: $RELEASE_TICKET_KEY"
          echo "is_test: $IS_TEST"
